# Generated by Django 3.2.9 on 2022-01-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='tel_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='staff_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
