# Generated by Django 3.2.9 on 2022-01-12 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0002_auto_20220112_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
