# Generated by Django 3.2.9 on 2022-01-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0003_learner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='date_enrolled',
            field=models.DateTimeField(null=True),
        ),
    ]
