# Generated by Django 3.2.9 on 2022-01-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0004_alter_learner_date_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='tel_number',
            field=models.IntegerField(null=True),
        ),
    ]
