# Generated by Django 3.2.9 on 2022-01-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0005_alter_mentor_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='second_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
