# Generated by Django 3.2.9 on 2022-01-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0006_alter_mentor_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
